import reference

# Source file name
DATA_SOURCE = "nesarc_pds.csv"

# Globals (using them to avoid errors caused by typos)
CODE = 'code'
MEANING = 'meaning'
VALUES = 'values'
SINGLE_VAR_TITLE = '\nResults for {} - {}\n'


# New variables
APPUREMIXED = 'APPUREMIXED'


# Maps to keep variables and their descriptions in order
ANIMALS_MAP = {
    CODE:'S8Q1A1',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF INSECTS, SNAKES, BIRDS, OTHER ANIMALS',
    VALUES: reference.ANIMALS_VALUES
}
AGE_MAP = {
    CODE: 'AGE',
    MEANING: 'AGE',
    VALUES: 'Age in years'
}
ORIGIN_MAP = {
    CODE: 'S1Q1E',
    MEANING: 'ORIGIN OR DESCENT',
    VALUES: reference.ORIGINS_VALUES
}
HEALTH_MAP = {
    CODE: 'S1Q16',
    MEANING: 'SELF-PERCEIVED CURRENT HEALTH',
    VALUES: reference.HEALTH_VALUES
}


# Other specific phobias
HEIGHTS_MAP = {
    CODE: 'S8Q1A2',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF HEIGHTS',
    VALUES: reference.HEIGHTS_VALUES
}

THUNDER_MAP = {
    CODE: 'S8Q1A3',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF STORMS, THUNDER, LIGHTNING',
    VALUES: reference.THUNDER_VALUES
}

WATER_MAP = {
    CODE: 'S8Q1A4',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF BEING IN/ON THE WATER',
    VALUES: reference.WATER_VALUES
}

FLYING_MAP = {
    CODE: 'S8Q1A5',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF FLYING',
    VALUES: reference.FLYING_VALUES
}

CROWD_MAP = {
    CODE: 'S8Q1A6',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF BEING IN CROWD/STANDING IN LINE',
    VALUES: reference.CROWD_VALUES
}

CLOSED_MAP = {
    CODE: 'S8Q1A7',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF BEING IN CLOSED SPACES',
    VALUES: reference.CLOSED_VALUES
}

BLOOD_MAP = {
    CODE: 'S8Q1A8',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF SEEING BLOOD/GETTING AN INJECTION',
    VALUES: reference.BLOOD_VALUES
}

TRAVELING_MAP = {
    CODE: 'S8Q1A9',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF TRAVELING IN BUSES/CARS/TRAINS',
    VALUES: reference.TRAVELING_VALUES
}

DENTIST_MAP = {
    CODE: 'S8Q1A10',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF GOING TO THE DENTIST',
    VALUES: reference.DENTIST_VALUES
}

HOSPITAL_MAP = {
    CODE: 'S8Q1A11',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF VISITING OR BEING IN A HOSPITAL',
    VALUES: reference.HOSPITAL_VALUES
}

OUTSIDE_MAP = {
    CODE: 'S8Q1A12',
    MEANING: 'EVER HAD FEAR/AVOIDANCE OF BEING OUTSIDE YOUR HOME ALONE',
    VALUES: reference.OUTSIDE_VALUES
}

# Other (animal phobia excluded) specific phobias as a list
SPECIFIC_PHOBIAS = [HEIGHTS_MAP, THUNDER_MAP, WATER_MAP, FLYING_MAP,
                    CROWD_MAP, CLOSED_MAP, BLOOD_MAP, TRAVELING_MAP,
                    DENTIST_MAP, HOSPITAL_MAP, OUTSIDE_MAP]